### ISSUE TITLE
"insufficient scopes" error

### ISSUE THREAD

**Issue by Aariq** [jthomasmock/gistillery#3]
`usethis::gh_token_help()` tells me I have a PAT that includes gists as a scope, but `gist_upload()` tells me I don't have the 'gist" scope.

``` r
usethis::gh_token_help()
#> • GitHub host: 'https://github.com'
#> • Personal access token for 'https://github.com': '<discovered>'
#> • GitHub user: 'Aariq'
#> • Token scopes: 'gist, repo, user, workflow'
#> • Email(s): 'scottericr@gmail.com (primary)', 'eric.scott@tufts.edu', 'ericscott@ufl.edu'

file <- tempfile()
cat("hello world", file = file)
gistillery::gist_upload(content=file, gist_name = "test.R")
#> Error: Requires authentication
#> 
#>   GitHub response headers suggest no or insufficient scopes
#>   To create gists you need the `gist` OAuth scope on your token.
```

<sup>Created on 2022-05-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Aariq** [comment]
I guess it requires that the GITHUB_PAT is set in .Renviron.  Is there a chance this could use `gitcreds` to get the PAT from a credential helper?

**Comment by jthomasmock** [comment]
I'm relying on `gistr::gist_auth()` for now as I'm experimenting with wrapping my own `httr2` based OAuth.

The `gistr::gist_auth()` function: https://github.com/ropensci/gistr/blob/HEAD/R/gist_auth.R#L34-L40

Requires a `GITHUB_PAT` with gist-scope in the `.Renviron`. This looks to conflict with `usethis`'s advice re: PAT. 🙃 

```
pat <- Sys.getenv("GITHUB_PAT", "")
  if (!identical(pat, "")) {
    auth_config <- list(auth_token=list(credentials=list(access_token=pat)))
  } else if (!interactive()) {
    stop("In non-interactive environments, please set GITHUB_PAT env to a GitHub",
         " access token (https://help.github.com/articles/creating-an-access-token-for-command-line-use)",
         call. = FALSE)
```

Let me look into the `gitcreds::gitcreds_get()` and see if I can wrap that in as an option.

**Comment by jthomasmock** [comment]
I can successfully use `gitcreds::gitcreds_get()` to get a token but will need to think about refactoring internal code to not use `gistr` for several functions as it uses `gist_auth()` internally without exposing direct ways of modifying it.
